"""
generate_sumo_scenarios.py
==========================
Generates SUMO route files for the three evaluation scenarios
(low, high, asymmetric) by running randomTrips.py + duarouter.

Prerequisites:
    - SUMO installed and SUMO_HOME environment variable set.
    - The 'medium' scenario must already exist (used as the base network).

Usage (from project root):
    python scripts/generate_sumo_scenarios.py

After running, each scenario directory will contain:
    intersections.net.xml  (copied from medium)
    vtypes.add.xml         (copied from medium)
    trips.trips.xml        (generated by randomTrips.py)
    traffic_test.rou.xml   (generated by duarouter)
    sumo_config.sumocfg    (already present)
"""

from __future__ import annotations

import os
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
EVAL_DIR  = ROOT / "sumo_configs" / "evaluation"
MEDIUM    = EVAL_DIR / "medium"
SUMO_HOME = Path(os.environ.get("SUMO_HOME", ""))

# ---------------------------------------------------------------------------
# Scenario definitions: period controls vehicle spawn rate (seconds/vehicle).
# Lower period = more vehicles.
# ---------------------------------------------------------------------------
SCENARIOS = {
    "low": {
        "period": 2.5,       # ~0.40 veh/s — light traffic
        "fringe_factor": 5,
        "end": 5400,
        "description": "Light traffic (~0.40 veh/s, fringe-factor 5)",
    },
    "high": {
        "period": 0.6,       # ~1.67 veh/s — heavy congestion
        "fringe_factor": 15,
        "end": 5400,
        "description": "Heavy traffic (~1.67 veh/s, fringe-factor 15)",
    },
    "asymmetric": {
        "period": 1.2,       # same rate as medium
        "fringe_factor": 10,
        "end": 5400,
        "description": "Asymmetric traffic: N-S dominant (fringe-factor 10, seeded differently)",
        "seed": 7,           # different seed → different route distribution
    },
}


def _find_tool(name: str) -> str:
    if not SUMO_HOME.is_dir():
        raise EnvironmentError(
            "SUMO_HOME is not set or does not exist. "
            "Install SUMO and set the SUMO_HOME environment variable."
        )
    candidates = [
        SUMO_HOME / "tools" / name,
        SUMO_HOME / "tools" / f"{name}.py",
    ]
    for c in candidates:
        if c.exists():
            return str(c)
    raise FileNotFoundError(f"SUMO tool not found: {name}  (searched in {SUMO_HOME / 'tools'})")


def _copy_base_files(scenario_dir: Path) -> None:
    for fname in ("intersections.net.xml", "vtypes.add.xml"):
        src = MEDIUM / fname
        dst = scenario_dir / fname
        if src.exists() and not dst.exists():
            shutil.copy2(src, dst)
            print(f"  Copied {fname}")


def _generate_trips(scenario_dir: Path, cfg: dict) -> Path:
    random_trips = _find_tool("randomTrips")
    net_file = scenario_dir / "intersections.net.xml"
    trips_file = scenario_dir / "trips.trips.xml"

    cmd = [
        sys.executable, random_trips,
        "-n", str(net_file),
        "-o", str(trips_file),
        "--trip-attributes",
        'type="mixed_traffic" departLane="random" departPos="random" departSpeed="random"',
        "--fringe-factor", str(cfg["fringe_factor"]),
        "--end", str(cfg["end"]),
        "--period", str(cfg["period"]),
        "--poisson",
        "--seed", str(cfg.get("seed", 42)),
        "--additional-files", str(scenario_dir / "vtypes.add.xml"),
    ]

    print(f"  Running randomTrips.py (period={cfg['period']})...")
    result = subprocess.run(cmd, capture_output=True, text=True)
    if result.returncode != 0:
        print(f"  ERROR: {result.stderr}")
        raise RuntimeError(f"randomTrips.py failed for {scenario_dir.name}")
    return trips_file


def _generate_routes(scenario_dir: Path, trips_file: Path) -> Path:
    duarouter = shutil.which("duarouter")
    if duarouter is None:
        raise FileNotFoundError(
            "duarouter not found in PATH. Make sure SUMO bin dir is in PATH."
        )

    net_file    = scenario_dir / "intersections.net.xml"
    routes_file = scenario_dir / "traffic_test.rou.xml"

    cmd = [
        duarouter,
        "-n", str(net_file),
        "-r", str(trips_file),
        "-o", str(routes_file),
        "--ignore-errors", "true",
        "--no-warnings", "true",
        "--no-step-log", "true",
    ]

    print("  Running duarouter...")
    # cwd=scenario_dir prevents duarouter from writing stray files to the project root
    result = subprocess.run(cmd, capture_output=True, text=True, cwd=str(scenario_dir))
    if result.returncode != 0:
        print(f"  ERROR: {result.stderr}")
        raise RuntimeError(f"duarouter failed for {scenario_dir.name}")
    return routes_file


def main() -> None:
    for name, cfg in SCENARIOS.items():
        scenario_dir = EVAL_DIR / name
        scenario_dir.mkdir(parents=True, exist_ok=True)

        print(f"\n{'='*50}")
        print(f"Scenario: {name}  —  {cfg['description']}")
        print(f"{'='*50}")

        _copy_base_files(scenario_dir)
        trips_file  = _generate_trips(scenario_dir, cfg)
        routes_file = _generate_routes(scenario_dir, trips_file)

        print(f"  Done: {routes_file.name} generated.")

    print("\nAll scenarios generated successfully.")
    print("Run evaluation with:")
    for name in SCENARIOS:
        print(f"  python experiment/runners/test_ppo.py  # update SUMO_CFG_PATH to evaluation/{name}/")


if __name__ == "__main__":
    main()
